robot_description: "robot_description"
trajectory_operator_plugin_name: "moveit_hybrid_planning/SimpleSampler"
local_constraint_solver_plugin_name: "moveit_hybrid_planning/ForwardTrajectory"
local_planning_frequency: 100.0
global_solution_topic: "global_trajectory"
local_solution_topic: "/scaled_joint_trajectory_controller/joint_trajectory" #"/forward_velocity_controller/commands"
local_solution_topic_type: "trajectory_msgs/JointTrajectory" #"std_msgs/Float64MultiArray"
publish_joint_positions: false
publish_joint_velocities: true
group_name: "ur_manipulator"
# Subscribe to this topic
monitored_planning_scene: "/planning_scene"
collision_object_topic: "/collision_object"
joint_states_topic: "/joint_states"

# ForwardTrajectory param
stop_before_collision: true
